const FOAM_FAMILIES={box:'Box',isoparette:'Isoparete',forzen:'Forzen'};
const FOAM_FORMULATIONS=['BCI','FP1','KIMPUR'];
function foamGreenRecipeLine(recipe,row,value){
  const columns=[
    ['Aire','L/min',row.air],['Espesor','mm',row.thickness],['Velocidad','m/min',row.speed],
    ['Presión ISO','bar',recipe.isoPressure],['Presión POL','bar',recipe.polyPressure],['Relación ISO / POL','',recipe.ratio],
    ['Tiempo de hilo','s',row.thread],
    [recipe.expander,'% sobre POL',row.expPercent],[recipe.expander,'kg/min',row.expKg],
    ['Catalizador amina (100 %)','% sobre POL',row.aminePercent],['Catalizador amina (100 %)','kg/min',row.amineKg],
    ['Aditivo agua (no total)','% sobre POL',row.waterPercent],['Aditivo agua (no total)','kg/min',row.waterKg],
    ['Temperatura POL','°C',row.polyTemp||recipe.polyTemp],['Temperatura ISO','°C',row.isoTemp],
    ['Inyector POL','Medida',recipe.polyInjector],['Poliolo','kg/min',row.polyFlow],
    ['Inyector ISO','Medida',row.isoInjector],['Isocianato','kg/min',row.isoFlow],['Tipo ISO','',row.isoType||recipe.isoType],
    ['Caudal total','kg/min',row.total],['N.º peine BASF','Caja · longitud',row.basfComb]
  ];
  return `<dl class="recipe-spec-grid recipe-large-default" aria-label="Datos de la receta en grande">${columns.map(([name,unit,data])=>`<div class="recipe-spec-item"><dt><span>${escapeHtml(name)}</span>${unit?`<small>${escapeHtml(unit)}</small>`:''}</dt><dd>${value(data)}</dd></div>`).join('')}</dl>`;
}
function foamGreenRecipe(selection){
  const formulation=selection.formulation,next=selection.next;
  if(!FOAM_FORMULATIONS.includes(formulation))return '';
  const heading=`Receta de ${formulation}`;
  if(!foamGreenLabel(next))return `<section class="foam-recipe"><strong>${heading}</strong><p>Selecciona el tipo de panel, espesor y ancho del panel siguiente para buscar su receta.</p></section>`;
  const label=foamGreenLabel(next);
  const matching=(state.foamGreenRecipes||[]).filter(item=>item.formulation===formulation&&item.family===next.family&&(item.width===next.width||item.allWidths===true));
  const candidates=matching.flatMap(recipe=>recipe.rows.filter(row=>row.thickness===next.thickness).map(row=>({recipe,row})));
  if(!candidates.length)return `<section class="foam-recipe"><strong>${heading}</strong><p>${escapeHtml(label)} · No hay una receta confirmada para esta combinación.</p></section>`;
  const value=(data,unit='')=>data===null||data===undefined?'<span class="foam-pending">Por confirmar</span>':escapeHtml(String(data).replaceAll('.',','))+(unit?' '+unit:'');
  const fields=(items)=>`<dl class="recipe-fields">${items.map(([name,data,unit])=>`<div><dt>${name}</dt><dd>${value(data,unit)}</dd></div>`).join('')}</dl>`;
  return `<section class="foam-recipe recipe-card"><div class="eyebrow">FORMULADO ${formulation} · PANEL SIGUIENTE</div><h3>${heading}</h3><p>${escapeHtml(label)}</p><p class="muted">${candidates.length} ${candidates.length===1?'fila de referencia':'filas de referencia'}. Abre la correspondiente a la velocidad indicada en tu orden; no se selecciona ninguna automáticamente.</p><div class="recipe-variants">${candidates.map(({recipe,row})=>`<details class="recipe-variant"><summary>Velocidad ${value(row.speed,'m/min')} · ${escapeHtml(recipe.pageLabel)}</summary><p class="recipe-source">Fuente: ${escapeHtml(recipe.source)} · ${escapeHtml(recipe.documentTitle)}</p><div class="recipe-group"><h4>Datos de la receta</h4>${foamGreenRecipeLine(recipe,row,value)}</div><div class="recipe-group"><h4>Condiciones de referencia</h4>${fields([['Temperatura chapa superior',recipe.upperSheet,'°C'],['Temperatura chapa inferior',recipe.lowerSheet,'°C'],['Temperatura prensa superior',recipe.upperPress,'°C'],['Temperatura prensa inferior',recipe.lowerPress,'°C'],['Densidad',recipe.density,'kg/m³'],['Aire de mezcla',recipe.airMix,'% sobre poliolo']])}</div>${recipe.note?`<p class="recipe-note">${escapeHtml(recipe.note)}</p>`:''}<p class="recipe-review">Documento marcado «En elaboración». Transcripción pendiente de validación por el responsable de planta.</p></details>`).join('')}</div></section>`;
}
function foamGreenBoxPhotos(selection){
  if(selection?.family!=='box'||![1000,1155].includes(selection.width))return '';
  const photos=state.foamGreenBoxPhotos||[];
  if(!photos.length)return '';
  return `<section class="panel foam-box-photos"><div class="foam-picker-head"><span class="foam-step">DX / SX</span><div><h2>Fotos de referencia · Box ${selection.width}</h2><p class="muted">Consulta las fotografías correspondientes a cada lado. Pulsa una imagen para verla a tamaño completo.</p></div></div><div class="foam-box-sides">${['dx','sx'].map(side=>`<section aria-label="Fotografías ${side.toUpperCase()}"><h3>Lado ${side.toUpperCase()}</h3><div class="foam-box-gallery">${photos.filter(photo=>photo.side===side).map((photo,index)=>`<figure><a ${privateMediaAttributes(photo.url,'href')} target="_blank" rel="noopener noreferrer" aria-label="Abrir foto ${side.toUpperCase()} ${index+1} a tamaño completo"><img ${privateMediaAttributes(photo.url)} alt="Referencia Box ${selection.width}, lado ${side.toUpperCase()}, foto ${index+1}" loading="lazy"></a><figcaption>${side.toUpperCase()} · Foto ${index+1}</figcaption></figure>`).join('')}</div></section>`).join('')}</div></section>`;
}
function foamGreenKey(){return `isopan-foam-green-${state.auth.user?.id||'sin-cuenta'}`;}
function foamGreenSelection(){if(!state.foamGreen){try{state.foamGreen=JSON.parse(localStorage.getItem(foamGreenKey())||'null');}catch{state.foamGreen=null;}if(!state.foamGreen||typeof state.foamGreen!=='object')state.foamGreen={};}return state.foamGreen;}
function foamGreenSave(){saveLocal(foamGreenKey(),foamGreenSelection());}
function foamGreenVariant(selection){if(!selection||!FOAM_FAMILIES[selection.family]||!Number.isInteger(selection.thickness)||!Number.isInteger(selection.width))return null;return state.foamGreenCatalog.filter(item=>item.family===selection.family&&item.thickness===selection.thickness&&item.width===selection.width);}
function foamGreenLabel(selection){return selection&&foamGreenVariant(selection)?.length?`${FOAM_FAMILIES[selection.family]} ${selection.thickness} · ${selection.width} mm`:'';}
function foamGreenMaterial(values){return values?.length?`<ul>${values.map(value=>`<li>${escapeHtml(value)}</li>`).join('')}</ul>`:'<span class="foam-pending">Sin dato en la ficha</span>';}
function foamGreenData(item){if(!item.settings)return '<div class="foam-empty">No hay datos transcritos para esta ficha. Consulta al responsable.</div>';return `<div class="foam-data"><div class="foam-data-title"><strong>Tapones SX y DX</strong><span>FICHA HISTÓRICA · SIN VALIDAR</span></div><div class="foam-data-sides">${[['sx','SX'],['dx','DX']].map(([key,label])=>{const side=item.settings[key]||{};return `<section><h3>${label}</h3><div class="foam-measures"><div><small>Altura del tapón</small><strong>${side.height?`${escapeHtml(side.height)} <em>mm</em>`:'<span class="foam-pending">Por confirmar</span>'}</strong></div><div><small>Profundidad del tapón</small><strong>${side.depth?`${escapeHtml(side.depth)} <em>mm</em>`:'<span class="foam-pending">Por confirmar</span>'}</strong></div></div>${Array.isArray(side.nastro)&&side.nastro.some(value=>String(value??'').trim())?`<div class="foam-materials"><small>Nastro</small>${foamGreenMaterial(side.nastro.filter(value=>String(value??'').trim()))}</div>`:''}${Array.isArray(side.guarnicion)&&side.guarnicion.some(value=>String(value??'').trim())?`<div class="foam-materials"><small>Guarnición</small>${foamGreenMaterial(side.guarnicion.filter(value=>String(value??'').trim()))}</div>`:''}</section>`;}).join('')}</div><p class="foam-review">${escapeHtml(item.review||'Confirmar la transcripción antes de su uso.')}</p></div>`;}
function foamGreenPicker(side,title){const selection=foamGreenSelection()[side]||{};const catalog=state.foamGreenCatalog.filter(item=>item.width!==null);const thicknesses=[...new Set(catalog.filter(item=>item.family===selection.family).map(item=>item.thickness))].sort((a,b)=>a-b);const widths=[...new Set(catalog.filter(item=>item.family===selection.family&&item.thickness===selection.thickness).map(item=>item.width))].sort((a,b)=>a-b);const matches=foamGreenVariant(selection)||[];return `<section class="panel foam-picker"><div class="foam-picker-head"><span class="foam-step">${side==='current'?'01':'02'}</span><div><h2>${title}</h2><p class="muted">Selecciona tipo, espesor y ancho de la orden de producción.</p></div></div><div class="foam-field"><strong>Tipo de panel</strong><div class="foam-options">${Object.entries(FOAM_FAMILIES).map(([id,label])=>`<button type="button" class="foam-option ${selection.family===id?'active':''}" data-foam-family="${id}" data-foam-side="${side}" aria-pressed="${selection.family===id}">${label}</button>`).join('')}</div></div>${selection.family?`<div class="foam-field"><strong>Espesor</strong><div class="foam-options">${thicknesses.map(value=>`<button type="button" class="foam-option ${selection.thickness===value?'active':''}" data-foam-thickness="${value}" data-foam-side="${side}" aria-pressed="${selection.thickness===value}">${value} mm</button>`).join('')}</div></div>`:''}${selection.thickness?`<div class="foam-field"><strong>Ancho</strong><div class="foam-options">${widths.map(value=>`<button type="button" class="foam-option ${selection.width===value?'active':''}" data-foam-width="${value}" data-foam-side="${side}" aria-pressed="${selection.width===value}">${value} mm</button>`).join('')}</div></div>`:''}${matches.length?`<div class="foam-picker-status">${matches.some(item=>item.settings)?'Ficha histórica disponible':'Ficha pendiente de transcribir'}${matches.length>1?` · ${matches.length} versiones`:''}</div>`:`<div class="foam-empty">${selection.family&&selection.thickness&&!widths.length?'El ancho de este panel queda pendiente de confirmar.':'Completa la selección para continuar.'}</div>`}</section>`;}
function foamGreenResult(a,line,selection,current,next){const matches=foamGreenVariant(selection.next)||[];const chosen=matches.find(item=>item.id===selection.recordId)||matches[0];const procedure=approvedProcedure(a,line,current,next);return back(`produccion/${a.id}/${encodeURIComponent(line)}`,'Volver a la línea')+pageHead('Espuma / Línea Verde','Ficha de preparación','Datos del panel siguiente para el cambio seleccionado.')+`<section class="panel foam-result"><div class="foam-result-heading"><div><div class="eyebrow">FORMULADO ${escapeHtml(selection.formulation)}</div><h2>De ${escapeHtml(current)} a ${escapeHtml(next)}</h2></div><button type="button" class="btn btn-outline" data-foam-edit>Modificar selección</button></div>${foamGreenRecipe(selection)}</section><section class="panel foam-result"><div class="foam-picker-head"><span class="foam-step">SX / DX</span><div><h2>Ajustes y materiales del panel siguiente</h2><p class="muted">Altura y profundidad de los tapones; nastro y guarnición de la ficha.</p></div></div>${matches.length>1?`<div class="foam-versions"><strong>Hay ${matches.length} fichas históricas con valores distintos. Elige cuál consultar:</strong><div class="foam-options">${matches.map((item,i)=>`<button type="button" class="foam-option ${chosen?.id===item.id?'active':''}" data-foam-record="${item.id}" aria-pressed="${chosen?.id===item.id}">Ficha ${i+1}</button>`).join('')}</div></div>`:''}${chosen?foamGreenData(chosen):'<div class="foam-empty">No hay ficha para esta variante.</div>'}</section>${foamGreenBoxPhotos(selection.next)}<div class="warning-panel foam-safety">${icon('alert')}<div><strong>Confirma los datos antes del cambio</strong><p>Estas cifras proceden de anotaciones históricas sin validar. Verifica variante, materiales y valores con la orden de producción y el responsable. Un campo sin dato no significa que el material no se necesite.</p></div></div>${procedure?`<section class="panel foam-result"><h2>Guía validada: ${escapeHtml(procedure.title)}</h2><p>Fuente: ${escapeHtml(procedure.source)} · Validado por: ${escapeHtml(procedure.validatedBy)}</p><ol class="guide-steps">${procedure.steps.map((step,i)=>`<li><span class="guide-step-number">${String(i+1).padStart(2,'0')}</span><div><strong>${escapeHtml(step.title)}</strong><p>${escapeHtml(step.instruction)}</p></div></li>`).join('')}</ol></section>`:''}`;}
function foamGreenPage(a,line){const selection=foamGreenSelection();const current=foamGreenLabel(selection.current),next=foamGreenLabel(selection.next);if(selection.view==='result'&&current&&next&&FOAM_FORMULATIONS.includes(selection.formulation))return foamGreenResult(a,line,selection,current,next);const uncertain=state.foamGreenCatalog.filter(item=>item.width===null);return back(`produccion/${a.id}/${encodeURIComponent(line)}`,'Volver a la línea')+pageHead('Espuma / Línea Verde','Preparar un cambio','Elige el formulado y los paneles. Después abre la ficha con los datos de SX, DX y materiales.')+`<section class="panel foam-formulation"><div class="foam-picker-head"><span class="foam-step">A</span><div><h2>Tipo de formulado</h2><p class="muted">Selecciona el formulado del cambio.</p></div></div><div class="foam-options foam-formula-options">${FOAM_FORMULATIONS.map(value=>`<button type="button" class="foam-option ${selection.formulation===value?'active':''}" data-foam-formulation="${value}" aria-pressed="${selection.formulation===value}">${value}</button>`).join('')}</div>${foamGreenRecipe(selection)}</section><div class="foam-pickers">${foamGreenPicker('current','Panel actual')}${foamGreenPicker('next','Panel siguiente')}</div>${foamGreenBoxPhotos(selection.next)}<section class="panel foam-result"><div class="foam-picker-head"><span class="foam-step">03</span><div><h2>Consultar preparación</h2><p class="muted">Tu selección se guarda en este navegador y en esta cuenta.</p></div></div>${current&&next?`<div class="foam-comparison"><div><small>DE</small><strong>${escapeHtml(current)}</strong></div><span aria-hidden="true">→</span><div><small>A</small><strong>${escapeHtml(next)}</strong></div></div>`:'<div class="foam-empty">Elige un panel actual y otro siguiente.</div>'}<div class="foam-actions"><button type="button" class="btn btn-primary" data-foam-show-result ${current&&next&&FOAM_FORMULATIONS.includes(selection.formulation)?'':'disabled'}>Ver ficha de preparación ${icon('arrow')}</button>${!selection.formulation?'<small>Elige también el tipo de formulado.</small>':''}</div></section>${uncertain.length?`<details class="panel foam-uncertain"><summary>Variantes pendientes de clasificar · ${uncertain.length}</summary><p>En estas hojas falta el ancho o aparecen varios anchos. No se asignan a ninguna variante hasta que se confirme.</p><div class="foam-uncertain-grid">${uncertain.map(item=>`<div><strong>${FOAM_FAMILIES[item.family]} ${item.thickness} · ancho por confirmar</strong>${item.note?`<small>${escapeHtml(item.note)}</small>`:''}</div>`).join('')}</div></details>`:''}`;}
function foamGreenClick(event){const button=event.target.closest('[data-foam-formulation],[data-foam-family],[data-foam-thickness],[data-foam-width],[data-foam-show-result],[data-foam-edit],[data-foam-record]');if(!button)return false;const selection=foamGreenSelection();if(button.dataset.foamShowResult!==undefined){if(!foamGreenLabel(selection.current)||!foamGreenLabel(selection.next)||!FOAM_FORMULATIONS.includes(selection.formulation))return true;selection.view='result';}else if(button.dataset.foamEdit!==undefined)selection.view='picker';else if(button.dataset.foamRecord)selection.recordId=button.dataset.foamRecord;else if(button.dataset.foamFormulation)selection.formulation=button.dataset.foamFormulation;else{const side=button.dataset.foamSide,entry=selection[side]||{};if(button.dataset.foamFamily)selection[side]={family:button.dataset.foamFamily};if(button.dataset.foamThickness)selection[side]={family:entry.family,thickness:Number(button.dataset.foamThickness)};if(button.dataset.foamWidth)selection[side]={...entry,width:Number(button.dataset.foamWidth)};selection.recordId=null;}foamGreenSave();const scroll=window.scrollY;render();window.scrollTo(0,button.dataset.foamShowResult!==undefined||button.dataset.foamEdit!==undefined?0:scroll);return true;}
